//
// Generated file, do not edit! Created by opp_msgtool 6.1 from WriteRequest.msg.
//

#ifndef __WRITEREQUEST_M_H
#define __WRITEREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class WriteRequest;
/**
 * Class generated from <tt>WriteRequest.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet WriteRequest
 * {
 *     int someField;
 *     string anotherField;
 *     double arrayField1[];
 *     double arrayField2[10];
 * }
 * </pre>
 */
class WriteRequest : public ::omnetpp::cPacket
{
  protected:
    int someField = 0;
    omnetpp::opp_string anotherField;
    double *arrayField1 = nullptr;
    size_t arrayField1_arraysize = 0;
    double arrayField2[10] = {0};

  private:
    void copy(const WriteRequest& other);

  protected:
    bool operator==(const WriteRequest&) = delete;

  public:
    WriteRequest(const char *name=nullptr, short kind=0);
    WriteRequest(const WriteRequest& other);
    virtual ~WriteRequest();
    WriteRequest& operator=(const WriteRequest& other);
    virtual WriteRequest *dup() const override {return new WriteRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSomeField() const;
    virtual void setSomeField(int someField);

    virtual const char * getAnotherField() const;
    virtual void setAnotherField(const char * anotherField);

    virtual void setArrayField1ArraySize(size_t size);
    virtual size_t getArrayField1ArraySize() const;
    virtual double getArrayField1(size_t k) const;
    virtual void setArrayField1(size_t k, double arrayField1);
    virtual void insertArrayField1(size_t k, double arrayField1);
    [[deprecated]] void insertArrayField1(double arrayField1) {appendArrayField1(arrayField1);}
    virtual void appendArrayField1(double arrayField1);
    virtual void eraseArrayField1(size_t k);

    virtual size_t getArrayField2ArraySize() const;
    virtual double getArrayField2(size_t k) const;
    virtual void setArrayField2(size_t k, double arrayField2);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WriteRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WriteRequest& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline WriteRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<WriteRequest*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __WRITEREQUEST_M_H

